# Стандартные флаги производительности Gradle
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Стиль кода Kotlin для Android
kotlin.code.style=official

# Обязательно для всех современных зависимостей AndroidX
android.useAndroidX=true

# R-класс каждого модуля не тянет ресурсы транзитивных зависимостей — быстрее сборка
android.nonTransitiveRClass=true
